// src/react/InactivityWarning.jsx
import React from "react";
import "./InactivityWarning.css";

/**
 * Componente React para mostrar advertencia de cierre de sesión por inactividad
 */
export function InactivityWarning({
  isVisible = false,
  timeRemaining = 0,
  title = "Sesión a punto de expirar",
  message = "Su sesión se cerrará automáticamente en:",
  instruction = "Mueva el mouse, haga click o presione cualquier tecla para continuar su sesión",
  extendButtonText = "Continuar sesión",
  logoutButtonText = "Cerrar sesión",
  showButtons = false,
  theme = "default",
  overlayClass = "",
  modalClass = "",
  iconClass = "",
  countdownClass = "",
  onExtend = () => {},
  onLogout = () => {},
  children,
}) {
  // Formatear tiempo restante
  const formatTimeRemaining = () => {
    const minutes = Math.floor(timeRemaining / 60);
    const seconds = timeRemaining % 60;
    return `${minutes}:${seconds.toString().padStart(2, "0")}`;
  };

  // Clases dinámicas basadas en el tema
  const computedOverlayClass = [
    "react-inactivity-warning-overlay",
    `react-inactivity-warning-theme-${theme}`,
    overlayClass,
  ]
    .filter(Boolean)
    .join(" ");

  const computedModalClass = [
    "react-inactivity-warning-modal",
    `react-inactivity-warning-modal-theme-${theme}`,
    modalClass,
  ]
    .filter(Boolean)
    .join(" ");

  const computedIconClass = [
    "react-inactivity-warning-icon",
    `react-inactivity-warning-icon-theme-${theme}`,
    iconClass,
  ]
    .filter(Boolean)
    .join(" ");

  const computedCountdownClass = [
    "react-inactivity-warning-countdown-circle",
    `react-inactivity-warning-countdown-theme-${theme}`,
    countdownClass,
  ]
    .filter(Boolean)
    .join(" ");

  if (!isVisible) {
    return null;
  }

  return (
    <div className={computedOverlayClass}>
      <div className={computedModalClass}>
        {/* Header */}
        <div className="react-inactivity-warning-header">
          <div className={computedIconClass}>
            {children?.icon || (
              <svg
                className="react-inactivity-warning-icon-svg"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            )}
          </div>
        </div>

        {/* Título */}
        <h3 className="react-inactivity-warning-title">
          {children?.title || title}
        </h3>

        {/* Mensaje */}
        <p className="react-inactivity-warning-message">
          {children?.message || message}
        </p>

        {/* Countdown */}
        <div className="react-inactivity-warning-countdown">
          <div className={computedCountdownClass}>
            <span className="react-inactivity-warning-countdown-text">
              {formatTimeRemaining()}
            </span>
          </div>
        </div>

        {/* Información adicional */}
        <p className="react-inactivity-warning-instruction">
          {children?.instruction || instruction}
        </p>

        {/* Botones de acción (opcional) */}
        {showButtons && (
          <div className="react-inactivity-warning-actions">
            <button
              onClick={onExtend}
              className="react-inactivity-warning-button react-inactivity-warning-button-primary"
            >
              {extendButtonText}
            </button>
            <button
              onClick={onLogout}
              className="react-inactivity-warning-button react-inactivity-warning-button-secondary"
            >
              {logoutButtonText}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default InactivityWarning;

// src/angular/inactivity-warning.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { InactivityTimerService } from './inactivity-timer.service'
import { Observable, Subscription } from 'rxjs'

@Component({
  selector: 'app-inactivity-warning',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div 
      *ngIf="isWarningVisible$ | async" 
      class="angular-inactivity-warning-overlay"
      [class]="overlayClass"
    >
      <div class="angular-inactivity-warning-modal" [class]="modalClass">
        <!-- Header -->
        <div class="angular-inactivity-warning-header">
          <div class="angular-inactivity-warning-icon" [class]="iconClass">
            <ng-content select="[slot=icon]">
              <svg class="angular-inactivity-warning-icon-svg" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
            </ng-content>
          </div>
        </div>
        
        <!-- Título -->
        <h3 class="angular-inactivity-warning-title">
          <ng-content select="[slot=title]">{{ title }}</ng-content>
        </h3>
        
        <!-- Mensaje -->
        <p class="angular-inactivity-warning-message">
          <ng-content select="[slot=message]">{{ message }}</ng-content>
        </p>
        
        <!-- Countdown -->
        <div class="angular-inactivity-warning-countdown">
          <div class="angular-inactivity-warning-countdown-circle" [class]="countdownClass">
            <span class="angular-inactivity-warning-countdown-text">
              {{ formatTimeRemaining() }}
            </span>
          </div>
        </div>
        
        <!-- Información adicional -->
        <p class="angular-inactivity-warning-instruction">
          <ng-content select="[slot=instruction]">{{ instruction }}</ng-content>
        </p>

        <!-- Botones de acción (opcional) -->
        <div *ngIf="showButtons" class="angular-inactivity-warning-actions">
          <button 
            (click)="onExtendSession()" 
            class="angular-inactivity-warning-button angular-inactivity-warning-button-primary"
          >
            {{ extendButtonText }}
          </button>
          <button 
            (click)="onLogoutNow()" 
            class="angular-inactivity-warning-button angular-inactivity-warning-button-secondary"
          >
            {{ logoutButtonText }}
          </button>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./inactivity-warning.component.css']
})
export class InactivityWarningComponent implements OnInit, OnDestroy {
  @Input() title: string = 'Sesión a punto de expirar'
  @Input() message: string = 'Su sesión se cerrará automáticamente en:'
  @Input() instruction: string = 'Mueva el mouse, haga click o presione cualquier tecla para continuar su sesión'
  @Input() extendButtonText: string = 'Continuar sesión'
  @Input() logoutButtonText: string = 'Cerrar sesión'
  @Input() showButtons: boolean = false
  @Input() theme: string = 'default'
  @Input() overlayClass: string = ''
  @Input() modalClass: string = ''
  @Input() iconClass: string = ''
  @Input() countdownClass: string = ''

  @Output() extend = new EventEmitter<void>()
  @Output() logout = new EventEmitter<void>()

  // Observables del servicio
  isWarningVisible$: Observable<boolean>
  timeRemaining$: Observable<number>
  isActive$: Observable<boolean>

  // Suscripciones
  private subscriptions: Subscription[] = []

  // Estado local
  timeRemaining: number = 0

  constructor(private inactivityTimerService: InactivityTimerService) {
    this.isWarningVisible$ = this.inactivityTimerService.isWarningVisible$
    this.timeRemaining$ = this.inactivityTimerService.timeRemaining$
    this.isActive$ = this.inactivityTimerService.isActive$
  }

  ngOnInit(): void {
    // Suscribirse a los cambios de timeRemaining para formatear
    const timeRemainingSub = this.timeRemaining$.subscribe(time => {
      this.timeRemaining = time
    })
    this.subscriptions.push(timeRemainingSub)
  }

  ngOnDestroy(): void {
    // Limpiar suscripciones
    this.subscriptions.forEach(sub => sub.unsubscribe())
  }

  /**
   * Formatea el tiempo restante en formato MM:SS
   */
  formatTimeRemaining(): string {
    const minutes = Math.floor(this.timeRemaining / 60)
    const seconds = this.timeRemaining % 60
    return `${minutes}:${seconds.toString().padStart(2, '0')}`
  }

  /**
   * Maneja la extensión de sesión
   */
  onExtendSession(): void {
    this.inactivityTimerService.extendSession()
    this.extend.emit()
  }

  /**
   * Maneja el cierre de sesión inmediato
   */
  onLogoutNow(): void {
    this.inactivityTimerService.stopMonitoring()
    this.logout.emit()
  }
}
